apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app-mabl
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-app-mabl
  template:
    metadata:
      labels:
        app: python-app-mabl
    spec:
      containers:
      - name: python-app-mabl-container
        image: python-app-mabl:1.0
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: python-app-mabl-service
spec:
  type: NodePort
  selector:
    app: python-app-mabl
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30008


